version: 2

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

conda:
  environment: docs/environment.yaml

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
