name: tudat-space-docs
channels:
  - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - sphinx_rtd_theme
  - sphinx-tabs
  - sphinx-copybutton
  - xorg-libxrender
  - xorg-libxpm
  - python-graphviz
  - pip
  - pip:
    - rtcat_sphinx_theme
    - sphinxcontrib-contentui
    - sphinxemoji
    - btd.sphinx.graphviz
