name: environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - sphinx
  - sphinx_rtd_theme
  - sphinx-panels
  - sphinx-tabs
  - sphinx-copybutton
  - nbsphinx
  - sphinx-gallery
  - ipython
  - pip
  - pip:
    - rtcat_sphinx_theme
    - sphinxcontrib-contentui

